backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: "static/images/uploads"

collections:
  - name: "dish"
    label: "Dish"
    folder: "content/dishes/"
    sort: "date:desc"
    create: true
    format: 'json'
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "entry-title", required: true}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
